<?php

namespace AppBundle\Repository;

/**
 * PlayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayRepository extends \Doctrine\ORM\EntityRepository
{
}
